# CMake generated Testfile for 
# Source directory: /home/tobiasosborne/Projects/convexfeld/tests
# Build directory: /home/tobiasosborne/Projects/convexfeld/build-profile/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_smoke "/home/tobiasosborne/Projects/convexfeld/build-profile/tests/test_smoke")
set_tests_properties(test_smoke PROPERTIES  _BACKTRACE_TRIPLES "/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;35;add_test;/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;43;add_cxf_test;/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;0;")
add_test(test_memory "/home/tobiasosborne/Projects/convexfeld/build-profile/tests/test_memory")
set_tests_properties(test_memory PROPERTIES  _BACKTRACE_TRIPLES "/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;35;add_test;/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;46;add_cxf_test;/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;0;")
add_test(test_matrix "/home/tobiasosborne/Projects/convexfeld/build-profile/tests/test_matrix")
set_tests_properties(test_matrix PROPERTIES  _BACKTRACE_TRIPLES "/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;35;add_test;/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;49;add_cxf_test;/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;0;")
add_test(test_basis "/home/tobiasosborne/Projects/convexfeld/build-profile/tests/test_basis")
set_tests_properties(test_basis PROPERTIES  _BACKTRACE_TRIPLES "/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;35;add_test;/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;53;add_cxf_test;/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;0;")
add_test(test_lu_factors "/home/tobiasosborne/Projects/convexfeld/build-profile/tests/test_lu_factors")
set_tests_properties(test_lu_factors PROPERTIES  _BACKTRACE_TRIPLES "/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;35;add_test;/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;57;add_cxf_test;/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;0;")
add_test(test_pricing "/home/tobiasosborne/Projects/convexfeld/build-profile/tests/test_pricing")
set_tests_properties(test_pricing PROPERTIES  _BACKTRACE_TRIPLES "/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;35;add_test;/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;60;add_cxf_test;/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;0;")
add_test(test_api_env "/home/tobiasosborne/Projects/convexfeld/build-profile/tests/test_api_env")
set_tests_properties(test_api_env PROPERTIES  _BACKTRACE_TRIPLES "/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;35;add_test;/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;64;add_cxf_test;/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;0;")
add_test(test_api_model "/home/tobiasosborne/Projects/convexfeld/build-profile/tests/test_api_model")
set_tests_properties(test_api_model PROPERTIES  _BACKTRACE_TRIPLES "/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;35;add_test;/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;67;add_cxf_test;/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;0;")
add_test(test_api_vars "/home/tobiasosborne/Projects/convexfeld/build-profile/tests/test_api_vars")
set_tests_properties(test_api_vars PROPERTIES  _BACKTRACE_TRIPLES "/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;35;add_test;/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;70;add_cxf_test;/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;0;")
add_test(test_memory_vectors "/home/tobiasosborne/Projects/convexfeld/build-profile/tests/test_memory_vectors")
set_tests_properties(test_memory_vectors PROPERTIES  _BACKTRACE_TRIPLES "/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;35;add_test;/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;73;add_cxf_test;/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;0;")
add_test(test_error "/home/tobiasosborne/Projects/convexfeld/build-profile/tests/test_error")
set_tests_properties(test_error PROPERTIES  _BACKTRACE_TRIPLES "/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;35;add_test;/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;76;add_cxf_test;/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;0;")
add_test(test_timing "/home/tobiasosborne/Projects/convexfeld/build-profile/tests/test_timing")
set_tests_properties(test_timing PROPERTIES  _BACKTRACE_TRIPLES "/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;35;add_test;/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;80;add_cxf_test;/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;0;")
add_test(test_analysis "/home/tobiasosborne/Projects/convexfeld/build-profile/tests/test_analysis")
set_tests_properties(test_analysis PROPERTIES  _BACKTRACE_TRIPLES "/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;35;add_test;/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;84;add_cxf_test;/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;0;")
add_test(test_api_constrs "/home/tobiasosborne/Projects/convexfeld/build-profile/tests/test_api_constrs")
set_tests_properties(test_api_constrs PROPERTIES  _BACKTRACE_TRIPLES "/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;35;add_test;/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;87;add_cxf_test;/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;0;")
add_test(test_api_optimize "/home/tobiasosborne/Projects/convexfeld/build-profile/tests/test_api_optimize")
set_tests_properties(test_api_optimize PROPERTIES  _BACKTRACE_TRIPLES "/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;35;add_test;/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;90;add_cxf_test;/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;0;")
add_test(test_api_query "/home/tobiasosborne/Projects/convexfeld/build-profile/tests/test_api_query")
set_tests_properties(test_api_query PROPERTIES  _BACKTRACE_TRIPLES "/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;35;add_test;/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;93;add_cxf_test;/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;0;")
add_test(test_logging "/home/tobiasosborne/Projects/convexfeld/build-profile/tests/test_logging")
set_tests_properties(test_logging PROPERTIES  _BACKTRACE_TRIPLES "/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;35;add_test;/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;96;add_cxf_test;/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;0;")
add_test(test_pivot_check "/home/tobiasosborne/Projects/convexfeld/build-profile/tests/test_pivot_check")
set_tests_properties(test_pivot_check PROPERTIES  _BACKTRACE_TRIPLES "/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;35;add_test;/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;100;add_cxf_test;/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;0;")
add_test(test_parameters "/home/tobiasosborne/Projects/convexfeld/build-profile/tests/test_parameters")
set_tests_properties(test_parameters PROPERTIES  _BACKTRACE_TRIPLES "/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;35;add_test;/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;104;add_cxf_test;/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;0;")
add_test(test_simplex_basic "/home/tobiasosborne/Projects/convexfeld/build-profile/tests/test_simplex_basic")
set_tests_properties(test_simplex_basic PROPERTIES  _BACKTRACE_TRIPLES "/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;35;add_test;/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;107;add_cxf_test;/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;0;")
add_test(test_callbacks "/home/tobiasosborne/Projects/convexfeld/build-profile/tests/test_callbacks")
set_tests_properties(test_callbacks PROPERTIES  _BACKTRACE_TRIPLES "/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;35;add_test;/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;110;add_cxf_test;/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;0;")
add_test(test_simplex_iteration "/home/tobiasosborne/Projects/convexfeld/build-profile/tests/test_simplex_iteration")
set_tests_properties(test_simplex_iteration PROPERTIES  _BACKTRACE_TRIPLES "/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;35;add_test;/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;114;add_cxf_test;/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;0;")
add_test(test_validation "/home/tobiasosborne/Projects/convexfeld/build-profile/tests/test_validation")
set_tests_properties(test_validation PROPERTIES  _BACKTRACE_TRIPLES "/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;35;add_test;/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;117;add_cxf_test;/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;0;")
add_test(test_threading "/home/tobiasosborne/Projects/convexfeld/build-profile/tests/test_threading")
set_tests_properties(test_threading PROPERTIES  _BACKTRACE_TRIPLES "/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;35;add_test;/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;121;add_cxf_test;/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;0;")
add_test(test_simplex_edge "/home/tobiasosborne/Projects/convexfeld/build-profile/tests/test_simplex_edge")
set_tests_properties(test_simplex_edge PROPERTIES  _BACKTRACE_TRIPLES "/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;35;add_test;/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;124;add_cxf_test;/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;0;")
add_test(test_pivot_eta "/home/tobiasosborne/Projects/convexfeld/build-profile/tests/test_pivot_eta")
set_tests_properties(test_pivot_eta PROPERTIES  _BACKTRACE_TRIPLES "/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;35;add_test;/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;127;add_cxf_test;/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;0;")
add_test(test_simplex_setup "/home/tobiasosborne/Projects/convexfeld/build-profile/tests/test_simplex_setup")
set_tests_properties(test_simplex_setup PROPERTIES  _BACKTRACE_TRIPLES "/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;35;add_test;/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;131;add_cxf_test;/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;0;")
add_test(test_solver_state "/home/tobiasosborne/Projects/convexfeld/build-profile/tests/test_solver_state")
set_tests_properties(test_solver_state PROPERTIES  _BACKTRACE_TRIPLES "/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;35;add_test;/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;135;add_cxf_test;/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;0;")
add_test(test_attrs_api "/home/tobiasosborne/Projects/convexfeld/build-profile/tests/test_attrs_api")
set_tests_properties(test_attrs_api PROPERTIES  _BACKTRACE_TRIPLES "/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;35;add_test;/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;138;add_cxf_test;/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;0;")
add_test(test_params_api "/home/tobiasosborne/Projects/convexfeld/build-profile/tests/test_params_api")
set_tests_properties(test_params_api PROPERTIES  _BACKTRACE_TRIPLES "/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;35;add_test;/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;141;add_cxf_test;/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;0;")
add_test(test_info_api "/home/tobiasosborne/Projects/convexfeld/build-profile/tests/test_info_api")
set_tests_properties(test_info_api PROPERTIES  _BACKTRACE_TRIPLES "/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;35;add_test;/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;144;add_cxf_test;/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;0;")
add_test(test_quadratic "/home/tobiasosborne/Projects/convexfeld/build-profile/tests/test_quadratic")
set_tests_properties(test_quadratic PROPERTIES  _BACKTRACE_TRIPLES "/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;35;add_test;/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;147;add_cxf_test;/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;0;")
add_test(test_mps_parser "/home/tobiasosborne/Projects/convexfeld/build-profile/tests/test_mps_parser")
set_tests_properties(test_mps_parser PROPERTIES  _BACKTRACE_TRIPLES "/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;35;add_test;/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;150;add_cxf_test;/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;0;")
add_test(test_mps_solve "/home/tobiasosborne/Projects/convexfeld/build-profile/tests/test_mps_solve")
set_tests_properties(test_mps_solve PROPERTIES  _BACKTRACE_TRIPLES "/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;35;add_test;/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;155;add_cxf_test;/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;0;")
add_test(test_tracer_bullet "/home/tobiasosborne/Projects/convexfeld/build-profile/tests/test_tracer_bullet")
set_tests_properties(test_tracer_bullet PROPERTIES  _BACKTRACE_TRIPLES "/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;35;add_test;/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;164;add_cxf_test;/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;0;")
add_test(test_constrained_lp "/home/tobiasosborne/Projects/convexfeld/build-profile/tests/test_constrained_lp")
set_tests_properties(test_constrained_lp PROPERTIES  _BACKTRACE_TRIPLES "/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;35;add_test;/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;167;add_cxf_test;/home/tobiasosborne/Projects/convexfeld/tests/CMakeLists.txt;0;")
